# Generated by Django 3.1.3 on 2022-09-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='useDate',
            field=models.DateTimeField(default='1900-01-01 00:00:00'),
        ),
    ]
