# Generated by Django 3.1.3 on 2022-09-02 20:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20220903_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='useDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 2, 20, 46, 1, 862793, tzinfo=utc)),
        ),
    ]
