# Generated by Django 3.1.3 on 2022-09-02 20:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20220903_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='regDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 2, 20, 53, 11, 369718, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='useDate',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0)),
        ),
    ]
